FROM python:3.12-slim
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
build-essential gcc libpq-dev
RUN mkdir -p /home/tmp/shm

WORKDIR /usr/app

COPY requirements.txt .
RUN pip install --index-url https://pypi.org/simple/ --extra-index-url https://utilities-pypi.timeresearch.biz   -r requirements.txt 

COPY . .

CMD [ "python", "-u", "port_run_tr.py" ]
